export const theme = {
  colors: {
    // Core brutalist palette (from reference)
    background: "#090909",
    card: "#111111",
    secondary: "#1A1A1A",
    border: "#2B2B2B",
    borderStrong: "#3A3A3A",
    text: "#FFFFFF",
    textSecondary: "#A5A5A5",
    textMuted: "#7A7A7A",
    accent: "#F5F5F5",
    accentMuted: "#D0D0D0",
    liked: "#F5F5F5",
    likedBg: "rgba(255,255,255,0.08)",
    danger: "#EF4444",
    success: "#10B981",
    overlay: "rgba(0,0,0,0.85)",
    overlayLight: "rgba(255,255,255,0.05)",

    // Legacy aliases (kept so existing components stay functional)
    bg: "#090909",
    surface: "#111111",
    surface2: "#1A1A1A",
    divider: "#2B2B2B",
    textDim: "#7A7A7A",
    textSoft: "#A5A5A5",
    brand: "#FFFFFF",
    brandLight: "#F5F5F5",
    brandDark: "#1A1A1A",
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
    xxxl: 64,
    xxxxl: 96,
  },
  radius: {
    none: 0,
    sm: 0,
    md: 2,
    lg: 4,
    xl: 6,
    pill: 4,
  },
  font: {
    display: 96,
    h1: 64,
    h2: 44,
    h3: 22,
    h4: 18,
    body: 15,
    bodyLarge: 17,
    bodySmall: 14,
    caption: 12,
    small: 11,
    tiny: 10,
    mono: 12,
  },
  fontWeight: {
    light: "300" as const,
    regular: "400" as const,
    medium: "500" as const,
    semibold: "600" as const,
    bold: "700" as const,
    heavy: "800" as const,
    black: "900" as const,
  },
  letterSpacing: {
    tight: -0.5,
    normal: 0,
    wide: 1,
    wider: 2,
    widest: 4,
    uppercase: 2,
  },
  shadows: {
    none: {},
    sharp: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.5,
      shadowRadius: 0,
      elevation: 8,
    },
    sharpLarge: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 16 },
      shadowOpacity: 0.5,
      shadowRadius: 0,
      elevation: 16,
    },
    card: {
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.4,
      shadowRadius: 0,
      elevation: 4,
    },
  },
  borderWidth: {
    thin: 1,
    medium: 2,
    thick: 3,
    heavy: 4,
  },
  opacity: {
    disabled: 0.4,
    pressed: 0.7,
    overlay: 0.6,
    overlayLight: 0.1,
  },
};

export type Theme = typeof theme;
